# Generated by Django 5.1.1 on 2024-12-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jbpjs_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50, null=True)),
                ('tanggungan_perusahaan', models.IntegerField(default=0)),
                ('add_by', models.CharField(blank=True, max_length=50, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_by', models.CharField(blank=True, max_length=50, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jenis_piutang_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_piutang', models.CharField(max_length=100)),
                ('add_by', models.CharField(max_length=100)),
                ('edit_by', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='kode_piutang_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50)),
                ('nama_kode', models.CharField(max_length=50)),
                ('inisial', models.CharField(blank=True, max_length=50, null=True)),
                ('add_by', models.CharField(blank=True, max_length=50, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_by', models.CharField(blank=True, max_length=50, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Kode Piutang',
                'verbose_name_plural': 'Kode Piutang',
            },
        ),
        migrations.CreateModel(
            name='kehilangan_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piutang', models.IntegerField()),
                ('pot_piutang', models.IntegerField()),
                ('pemutihan', models.IntegerField()),
                ('add_by', models.CharField(max_length=100)),
                ('edit_by', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.pegawai_db')),
            ],
        ),
        migrations.CreateModel(
            name='ketemu_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ketemu', models.IntegerField()),
                ('pemutihan', models.IntegerField()),
                ('add_by', models.CharField(max_length=100)),
                ('edit_by', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.pegawai_db')),
            ],
        ),
        migrations.CreateModel(
            name='no_dokumen_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodok', models.IntegerField(default=0)),
                ('kode_piutang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.kode_piutang_db')),
            ],
        ),
        migrations.CreateModel(
            name='piutang_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piutang', models.IntegerField()),
                ('pot_piutang', models.IntegerField()),
                ('pemutihan', models.IntegerField()),
                ('add_by', models.CharField(max_length=100)),
                ('edit_by', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.pegawai_db')),
            ],
        ),
        migrations.CreateModel(
            name='temporary_piutang_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piutang', models.IntegerField()),
                ('pot_piutang', models.IntegerField()),
                ('add_by', models.CharField(max_length=100)),
                ('edit_by', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.pegawai_db')),
            ],
        ),
        migrations.CreateModel(
            name='transaksi_piutang_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateField()),
                ('nodok', models.CharField(max_length=200)),
                ('kode_piutang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.kode_piutang_db')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.pegawai_db')),
            ],
        ),
    ]
