# Generated by Django 5.1.1 on 2024-12-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_jbpjs_db_jenis_piutang_db_kode_piutang_db_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi_piutang_db',
            name='nilai',
            field=models.IntegerField(null=True),
        ),
    ]
