# Generated by Django 5.1.1 on 2024-12-13 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_transaksi_piutang_db_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi_piutang_db',
            name='jenis_piutang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.jenis_piutang_db'),
        ),
    ]
