# Generated by Django 5.1.1 on 2024-12-13 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_transaksi_piutang_db_jenis_piutang'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary_piutang_db',
            name='jenis_piutang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.jenis_piutang_db'),
        ),
        migrations.AddField(
            model_name='temporary_piutang_db',
            name='tgl',
            field=models.DateField(null=True),
        ),
    ]
