# Generated by Django 5.1.1 on 2024-12-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0005_temporary_piutang_db_jenis_piutang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jenis_transaksi_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_transaksi', models.CharField(max_length=100)),
                ('add_by', models.CharField(max_length=100)),
                ('edit_by', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transaksi_piutang_db',
            name='jenis_piutang',
        ),
        migrations.AddField(
            model_name='transaksi_piutang_db',
            name='add_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaksi_piutang_db',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaksi_piutang_db',
            name='edit_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaksi_piutang_db',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaksi_piutang_db',
            name='jenis_transaksi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.jenis_transaksi_db'),
        ),
    ]
