# Generated by Django 5.1.1 on 2024-12-13 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_jenis_transaksi_db_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transaksi_piutang_db',
            new_name='transaksi_db',
        ),
        migrations.AlterField(
            model_name='jenis_piutang_db',
            name='jenis_piutang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.jenis_transaksi_db'),
        ),
    ]
