# Generated by Django 5.1.1 on 2024-12-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_rename_transaksi_piutang_db_transaksi_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenis_piutang_db',
            name='add_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jenis_piutang_db',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jenis_piutang_db',
            name='edit_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jenis_piutang_db',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jenis_transaksi_db',
            name='add_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jenis_transaksi_db',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jenis_transaksi_db',
            name='edit_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jenis_transaksi_db',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='kehilangan_db',
            name='add_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kehilangan_db',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='kehilangan_db',
            name='edit_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kehilangan_db',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ketemu_db',
            name='add_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ketemu_db',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ketemu_db',
            name='edit_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ketemu_db',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='piutang_db',
            name='add_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='piutang_db',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='piutang_db',
            name='edit_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='piutang_db',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='temporary_piutang_db',
            name='add_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temporary_piutang_db',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='temporary_piutang_db',
            name='edit_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temporary_piutang_db',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
