# Generated by Django 5.1.1 on 2024-12-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0009_alter_jenis_piutang_db_add_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jenis_piutang_db',
            old_name='jenis_piutang',
            new_name='jenis_transaksi',
        ),
    ]
