# Generated by Django 5.1.1 on 2024-12-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0010_rename_jenis_piutang_jenis_piutang_db_jenis_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi_db',
            name='kode_piutang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.kode_piutang_db'),
        ),
        migrations.AlterField(
            model_name='transaksi_db',
            name='nodok',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
