# Generated by Django 5.1.1 on 2024-12-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0011_alter_transaksi_db_kode_piutang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketemu_db',
            name='pemutihan',
            field=models.IntegerField(null=True),
        ),
    ]
