# Generated by Django 5.1.1 on 2024-12-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0012_alter_ketemu_db_pemutihan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaji_db',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
