# Generated by Django 5.1.1 on 2024-12-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0013_gaji_db_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_ijin_db',
            old_name='alfa',
            new_name='af',
        ),
    ]
