# Generated by Django 5.1.1 on 2024-12-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0014_rename_alfa_data_ijin_db_af'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaji_db',
            name='status_ebpjs_ks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gaji_db',
            name='status_ebpjs_tk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gaji_db',
            name='status_pothr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gaji_db',
            name='status_potpiutang',
            field=models.IntegerField(default=0),
        ),
    ]
