# Generated by Django 5.1.1 on 2024-12-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0015_gaji_db_status_ebpjs_ks_gaji_db_status_ebpjs_tk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekening_db',
            name='nama_rekening',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
