# Generated by Django 5.1.1 on 2024-12-24 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0016_rekening_db_nama_rekening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai_db',
            name='rek_sd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll_app.rekening_db'),
        ),
    ]
